# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

stages:
  - stage: build
    jobs:
    - job: run_build
      pool:
        vmImage: ubuntu-latest
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - task: CMake@1
        inputs:
          cmakeArgs: 
            Makefile
          workingDirectory: '$(System.DefaultWorkingDirectory)/P09/full_credit'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
          ./Shapes
        displayName: 'Run a multi-line script'
        workingDirectory: '$(System.DefaultWorkingDirectory)/P09/full_credit'

      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(System.DefaultWorkingDirectory)/P09/full_credit'
          contents: |      
            **/*.o
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: drop

  - stage: deploy
    jobs:
    - deployment: DeployTest
      displayName: 'Deploy to Development Environment
      pool:
        vmImage: ubuntu-latest'
      environment:
        name: 'Aadhitya_Deployment_Server'
        #resourceName: LAPTOP-I73C2NHS
        resourceType: virtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none

            - task: CopyFiles@2
              inputs:
                sourceFolder: '$(Build.ArtifactStagingDirectory)\drop'
                contents: |      
                  **/*.o
                targetFolder: 'C:\AzureDevops\DeploymentTest'