# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: build
    jobs:
    - job: run_build
      pool:
        vmImage: 'windows-latest'
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Azure/IIS'

      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(System.DefaultWorkingDirectory)/Azure/IIS'
          contents: |      
            **/*.html
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: drop

  - stage: deploy_dev
    jobs:
    - deployment: DeployDev
      displayName: 'Deploy to Development Environment
      pool:
        vmImage: windows-latest'
      environment:
        name: 'Aadhitya_Deployment_Server'
        #resourceName: LAPTOP-I73C2NHS
        resourceType: virtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: drop
                targetPath: 'C:\inetpub\wwwroot\MyWebsiteAzure'
                patterns: '**/*.html'

            - task: IISWebAppManagementOnMachineGroup@0
              inputs:
                IISDeploymentType: 'IISWebsite'
                ActionIISWebsite: 'CreateOrUpdateWebsite'
                WebsiteName: 'MyWebsiteAzure'
                WebsitePhysicalPath: 'C:\inetpub\wwwroot\MyWebsiteAzure'
                WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
                CreateOrUpdateAppPoolForWebsite: true
                AppPoolNameForWebsite: 'MyWebsiteAzure'
                DotNetVersionForWebsite: 'No Managed Code'
                PipeLineModeForWebsite: 'Integrated'
                AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
                AddBinding: true
                Bindings: |
                    {
                        bindings:[
                            {
                                "protocol":"http",
                                "ipAddress":"",
                                "hostname":"",
                                "port":"80",
                                "sslThumbprint":"",
                                "sniFlag":false
                            }
                        ]
                    }

  - stage: deploy_test
    jobs:
    - deployment: DeployTest
      displayName: 'Deploy to Test Environment
      pool:
        vmImage: windows-latest'
      environment:
        name: 'Test_Anv'
        #resourceName: LAPTOP-I73C2NHS
        resourceType: virtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: drop
                targetPath: 'C:\inetpub\wwwroot\MyWebsiteAzure'
                patterns: '**/anvita.html'

            - task: IISWebAppManagementOnMachineGroup@0
              inputs:
                IISDeploymentType: 'IISWebsite'
                ActionIISWebsite: 'CreateOrUpdateWebsite'
                WebsiteName: 'MyWebsiteAzure'
                WebsitePhysicalPath: 'C:\inetpub\wwwroot\MyWebsiteAzure'
                WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
                CreateOrUpdateAppPoolForWebsite: true
                AppPoolNameForWebsite: 'MyWebsiteAzure'
                DotNetVersionForWebsite: 'No Managed Code'
                PipeLineModeForWebsite: 'Integrated'
                AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
                AddBinding: true
                Bindings: |
                    {
                        bindings:[
                            {
                                "protocol":"http",
                                "ipAddress":"",
                                "hostname":"mywebsiteazure.local",
                                "port":"80",
                                "sslThumbprint":"",
                                "sniFlag":false
                            }
                        ]
                    }