# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

stages:
  - stage: build
    jobs:
    - job: run_build
      pool:
        vmImage: windows-latest
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Azure/SQL'


  
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(System.DefaultWorkingDirectory)/Azure/SQL'
          contents: |      
            **/*.sql
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: drop

  - stage: deploy
    jobs:
    - deployment: DeployTest
      displayName: 'Deploy to Development Environment
      pool:
        vmImage: ubuntu-latest'
      environment:
        name: 'Aadhitya_Deployment_Server'
        #resourceName: LAPTOP-I73C2NHS
        resourceType: virtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                targetPath: 'C:\AzureDevops\sql'

            - task: SqlDacpacDeploymentOnMachineGroup@0
              inputs:
                TaskType: 'sqlQuery'
                SqlFile: 'C:\AzureDevops\sql\drop\publication.sql'
                ServerName: 'LAPTOP-I73C2NHS\SQLEXPRESS'
                DatabaseName: 'AppTest'
                AuthScheme: 'windowsAuthentication'

            - task: SqlDacpacDeploymentOnMachineGroup@0
              inputs:
                TaskType: 'sqlInline'
                InlineSql: 'SELECT *  From Publication;'
                ServerName: 'LAPTOP-I73C2NHS\SQLEXPRESS'
                DatabaseName: 'AppTest'
                AuthScheme: 'windowsAuthentication'
